JOIN > DATA SEARCHING FROM MULTIPLE TABLE 
> 시스템 내부에서 조인 대상 테이블들을 하나의 테이블로 조합
> 테이블들의 행을 하나의 행으로 조합
> 행을 조합할 때 반드시 무결성이 보장이 되도록 조합
> 무결성 보장을 위해 조건이 필요(DEPARTMENT_ID == )
> 조인 조건 : n-1 에 해당하는 조인 조건을 WHERE 절에 반드시 명시
> 조인 조건을 생략하거나 잘못 작성할 경우 CARTESIAN PRODUCT 발생

 - EQUAL JOIN : =
  > 키 값이 같은 경우 조인
 - NON-EQUAL JOIN
  > 키 값이 아닌 값(수치 등)을 조인
 - OUTER JOIN : (+) 
  > 키 값이 없는 경우 키 값을 추가 후 조인
 - SELF JOIN

SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY NOT IN (2500, 5000, 7500)
AND JOB_ID IN('SA_REP', 'ST_CLERK')
ORDER BY LAST_NAME ASC;

SELECT E.LAST_NAME, D.DEPARTMENT_NAME, E.DEPARTMENT_ID
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND (D.DEPARTMENT_ID = 90
OR E.DEPARTMENT_ID = 50)
AND E.LAST_NAME LIKE '%a%'
ORDER BY E.LAST_NAME;

SELECT E.EMPLOYEE_ID, E.LAST_NAME, D.DEPARTMENT_NAME, D.DEPARTMENT_ID
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT E.LAST_NAME, E.SALARY, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND E.SALARY >= 15000;

SELECT E.LAST_NAME, E.SALARY*12 "AnnSal", D.DEPARTMENT_NAME, D.LOCATION_ID
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND E.SALARY*12 > 150000;

SELECT E.LAST_NAME, D.DEPARTMENT_NAME, L.LOCATION_ID, L.CITY
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND D.LOCATION_ID = L.LOCATION_ID
AND E.COMMISSION_PCT IS NOT NULL;

SELECT E.LAST_NAME, D.DEPARTMENT_NAME,D.DEPARTMENT_ID
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID(+) = D.DEPARTMENT_ID
ORDER BY D.DEPARTMENT_ID ASC;

SELECT E.LAST_NAME, E.SALARY, J.GRADE
FROM EMPLOYEES E, SALGRADE J
WHERE E.SALARY
BETWEEN J.LOSAL AND J.HISAL;

SELECT E.LAST_NAME, E.SALARY, J.GRADE
FROM EMPLOYEES E, SALGRADE J
WHERE E.SALARY BETWEEN J.LOSAL AND J.HISAL
AND J.GRADE = 4
ORDER BY E.SALARY DESC;