서브쿼리
 - 서브쿼리 결과가 단일일 경우 =, > 같은 단일 연산자 사용
 - 서브쿼리 결과가 다수일 경우 in 과 같은 복수 연산자 사용
 - 서브쿼리 컬럼과 메인쿼리 컬럼의 데이터 타입은 단드시 같아야 함
 - 대부분 서브쿼리와 메인쿼리 컬럼의 이름이 동일함


IN, ALL, ANY 연산자
결과가 30, 40일 때
IN (결과) -> 30, 40
 > ALL (결과 전부 보다 큰값) -> 50, 60
 < ALL (결과 전부 보다 작은값) -> 10, 20
 >= ANY (최소값 보다 큰값) -> 40, 50, 60
 < ANY (최대값 보다 작은값) -> 10, 20, 30


SELECT MANAGER_ID, MIN(SALARY) AS MINSAL
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID
HAVING MIN(SALARY) >= 5000
ORDER BY MINSAL;

SELECT D.DEPARTMENT_ID, D.LOCATION_ID, COUNT(E.EMPLOYEE_ID), AVG(E.SALARY) AS AVGSAL
FROM DEPARTMENTS D, EMPLOYEES E
WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.LOCATION_ID
ORDER BY D.LOCATION_ID;

SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (
    SELECT SALARY 
    FROM EMPLOYEES
    WHERE LAST_NAME = 'Abel')
ORDER BY SALARY DESC;

SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID = (
    SELECT JOB_ID
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 141
);

SELECT LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE JOB_ID = (
    SELECT JOB_ID
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 141
)
AND SALARY > (
    SELECT SALARY
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 143
)
ORDER BY SALARY DESC;

SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
    SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
    WHERE DEPARTMENT_NAME = 'IT'
)
ORDER BY SALARY DESC;

SELECT DEPARTMENT_ID, MIN(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MIN(SALARY) > (
    SELECT MIN(SALARY)
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 50
);

SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID = (
    SELECT JOB_ID
    FROM EMPLOYEES
    WHERE LAST_NAME = 'Haas'
);

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES
WHERE SALARY < ALL (
    SELECT DISTINCT SALARY
    FROM EMPLOYEES
    WHERE JOB_ID = 'IT_PROG'
)
ORDER BY SALARY;

SELECT LAST_NAME, EMPLOYEE_ID, HIRE_DATE
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE LAST_NAME = 'Zlotkey'
)
AND LAST_NAME != 'Zlotkey'
ORDER BY HIRE_DATE;

SELECT LAST_NAME, EMPLOYEE_ID, SALARY
FROM EMPLOYEES
WHERE SALARY > (
    SELECT AVG(SALARY) AS AVGSAL
    FROM EMPLOYEES
)
ORDER BY SALARY DESC;

SELECT LAST_NAME, EMPLOYEE_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE LAST_NAME LIKE '%u%'
)
AND LAST_NAME NOT LIKE '%u%'
ORDER BY LAST_NAME;