CREATE TABLE DEPT(
// 컬럼 선언부
    DID NUMBER(3) CONSTRAINT DEPT_DID_PK PRIMARY KEY,
    DNAME CHAR(5),
    LOC NUMBER(3),
    CONSTRAINT DEPT_DNAME_UK UNIQUE(DANME)
);

CONSTRAINT 제약조건명 제약조건유형(컬럼 이름)

 제약조건 선언
COLUMN 레벨에서의 선언
TABLE 레벨에서의 선언 - 가독성 좋음

FOREIGN
DEPARTMENT_ID NUMBER(4),
CONSTRAINT EMP_DEPT_FK FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DEPARTMENTS(DEPARTMENT_ID),
CONSTRAINT EMP_EMAIL_UK UNIQUE(EMAIL)

PRIMARY KEY FOREIGN KEY
DATA_TYPE 와 DATA_SIZE 가 같아야 함

ON DELETE CASCADE : 종속적인 삭제
ON DELETE SET NULL : 부모 테이블 삭제 & 자식 테이블 NULL

DROP TABLE TEST CASCADE CONSTRAINTS;
DROP TABLE TEST1 CASCADE CONSTRAINTS;

======= test.sql =======
CREATE TABLE TEST(
    a NUMBER(5),
    b NUMBER(5) NOT NULL,
    c NUMBER(5),
    CONSTRAINT TEST_A_PK PRIMARY KEY(a),
    CONSTRAINT TEST_B_CK CHECK(b IN (0, 1)),
    CONSTRAINT TEST_C_UK UNIQUE(c)
);

CREATE TABLE TEST1(
    d NUMBER(5), 
    e NUMBER(5) NOT NULL,
    f NUMBER(5),
    a NUMBER(5),
    CONSTRAINT TEST1_D_PK PRIMARY KEY(d),
    CONSTRAINT TEST1_A_FK FOREIGN KEY(a)
    REFERENCES TEST(a)
);

COMMIT;

======= TABLE =======
DROP TABLE DEPT CASCADE CONSTRAINTS;
DROP TABLE EMP CASCADE CONSTRAINTS;

CREATE TABLE DEPT(
    DEPTNO NUMBER(2),
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13),
    CONSTRAINT DEPT_DEPTNO_PK PRIMARY KEY(DEPTNO)
);

CREATE TABLE EMP(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10) NOT NULL,
    GENDER CHAR(10) NOT NULL,
    JOB VARCHAR2(9) NOT NULL,
    MRG NUMBER(4),
    HIREDATE DATE NOT NULL,
    SAL NUMBER(7, 2) NOT NULL,
    COMM NUMBER(7, 2),
    DEPTNO NUMBER(2),
    CONSTRAINT EMP_EMPNO_PK PRIMARY KEY(EMPNO),
    CONSTRAINT EMP_GENDER_CK CHECK(GENDER IN ('MAN', 'WOMAN')),
    CONSTRAINT EMP_DEPTNO_FK FOREIGN KEY(DEPTNO)
    REFERENCES DEPT(DEPTNO)
);

INSERT INTO DEPT
VALUES (10, 'Adminstration', 1700);
INSERT INTO DEPT
VALUES (20, 'Marketing', 1800);
INSERT INTO DEPT
VALUES (30, 'Purchasing', 1700);
INSERT INTO DEPT
VALUES (40, 'Human', 2400);
INSERT INTO DEPT
VALUES (50, 'Shipping', 1500);

INSERT INTO EMP
VALUES (100, 'King', 'MAN', 'AD_PRES', NULL, '1987-01-17', 24000, NULL, 10);
INSERT INTO EMP
VALUES (101, 'Kochar', 'MAN', 'AD_VP', 100, '1989-09-21', 24000, NULL, 50);
INSERT INTO EMP
VALUES (102, 'DE Haen', 'WOMAN', 'AD_VP', 100, '1993-01-13', 24000, NULL, 50);
INSERT INTO EMP
VALUES (103, 'Hunold', 'MAN', 'IT_PROG', 102, '1990-07-03', 24000, NULL, 40);
INSERT INTO EMP
VALUES (104, 'Ernst', 'WOMAN', 'IT_PROG', 103, '1997-07-25', 24000, NULL, 40);

ALTER TABLE EMP
MODIFY (GENDER CHAR(11));

SELECT * FROM DEPT;
SELECT * FROM EMP;

DESC DEPT
DESC EMP

COMMIT;

=======================================================
CREATE VIEW SALVU50
AS
SELECT EMPLOYEE_ID AS ID_NUMBER, LAST_NAME AS NAME, SALARY*12 AS ANN_SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = '50';

CREATE VIEW DEPT_SUM_VU
AS
SELECT DEPARTMENT_ID, MIN(SALARY) AS MINSAL, MAX(SALARY) AS MAXSAL, AVG(SALARY) AS AVGSAL
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT E.DEPARTMENT_ID, E.LAST_NAME, E.SALARY, D.MINSAL
FROM EMPLOYEES E, DEPT_SUM_VU D 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND E.SALARY = D.MINSAL;

SELECT ROWNUM, LAST_NAME, SALARY
FROM (
    SELECT LAST_NAME, SALARY
    FROM EMPLOYEES
    ORDER BY SALARY DESC)
WHERE ROWNUM < 4;

SELECT DEPARTMENT_ID, AVGSAL
FROM (
    SELECT DEPARTMENT_ID, AVG(SALARY) AS AVGSAL
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
    ORDER BY AVG(SALARY) DESC
)
WHERE ROWNUM < 5;

CREATE SEQUENCE DEPT_DEPTID_SEQ
INCREMENT BY 10 > SN 증가 값
START WITH 120 > 첫번째 생성되는 SN
MAXVALUE 9999 > 가장 마지막에 생성되는 SN
NOCACHE > 캐싱 (거의 사용 안함)
NOCYCLE; > 반복 (거의 사용 안함)

CREATE SEQUENCE DEPT_DEPTID_SEQ
INCREMENT BY 10
START WITH 300
MAXVALUE 9999;

INSERT INTO DEPARTMENTS
VALUES (DEPT_DEPTID_SEQ.NEXTVAL, 'AA', 100, 1700);

TABLE 은 공유하지 않음
SEQUENCE 는 공유 가능

ALTER SEQUENCE DEPT_DEPTID_SEQ
INCREMENT BY 20
MAXVALUE 999999;

ㄴ> START WITH 는 절대로 변경할 수 없다.

DROP SEQUENCE DEPT_DEPTID_SEQ;

DELETE FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'AA';

INDEX : ELEVATOR, 목차의 개념
 - 데이터, 행의 주소를 저장
 - 성능과 직결, TUNNING의 영역
 - PK, FK, UK 생성 시 인덱스도 생성
 - 중복 불가

CREATE SYNONYM D_SUM 
FOR DEPT_SUM_VU;