연산자
 - BETWEEN (이상) AND (이하)
 - IN(set) : set을 포함
 - LIKE : =, 포함
 - IS NULL : NULL VALUE

 - AND / && / *
 - OR / || / +
 - NOT / ! / -

% : 시작, 끝
%()% : () 를 포함
Ex) WHERE HIRE_DATE LIKE '05/%'

ORDER BY () : 정렬
Ex) ORDER BY "AnnSal"

ASC, DESC : 오름차순 내림차순


SELECT LAST_NAME, MANAGER_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

SELECT LAST_NAME, JOB_ID, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL;

SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90
AND SALARY >= 15000;

SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID
NOT IN ('IT_PROG', 'ST_CLERK', 'SA_REP');

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID,SALARY
FROM EMPLOYEES
WHERE JOB_ID = 'SA_REP'
OR JOB_ID = 'AD_PRES'
AND SALARY > 15000;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY*12 "AnnSal"
FROM EMPLOYEES
ORDER BY "AnnSal";

SELECT LAST_NAME, SALARY*12 "AnnSal"
FROM EMPLOYEES
WHERE SALARY*12 >= 120000;

SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 176;

SELECT LAST_NAME, SALARY*12 "AnnSal"
FROM EMPLOYEES
WHERE SALARY*12 BETWEEN 150000 AND 200000;

SELECT LAST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '03/01/01' AND '05/05/30'
ORDER BY HIRE_DATE DESC;

SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(20, 50)
ORDER BY LAST_NAME ASC;

SELECT LAST_NAME, SALARY*12 "AnnSal"
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(20, 50)
AND SALARY*12 BETWEEN 200000 AND 250000;

SELECT LAST_NAME, SALARY*12 "AnnSal"
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20
OR DEPARTMENT_ID = 50
AND SALARY*12 >= 100000;

SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE LIKE '06/%';
WHERE HIRE_DATE BETWEEN '06/01/01' AND '06/12/31';

SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

SELECT LAST_NAME, JOB_ID, MANAGER_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL;

SELECT LAST_NAME, SALARY*12 AS ANNSAL, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY ANNSAL DESC;

SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '___a%';

SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%a%'
AND LAST_NAME LIKE '%e%';

SELECT LAST_NAME, SALARY, JOB_ID
FROM EMPLOYEES
WHERE SALARY NOT IN(2500, 3500, 7000)
AND JOB_ID IN('SA_REP', 'ST_CLERK');

SELECT DISTINCT JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(30, 90)
ORDER BY JOB_ID;

